name: CI & Despliegue a GitHub Pass

on:
  push:
    branches: ["main", "frontend"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

  concurrency:
    group: "CI-CD-GHPages"
    cancel-in-progress: true

jobs:
  verificar_codigo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        name: Mostrar archivos (opcional para depurar)
        run: ls -R

        name: verificar archivos principales
        run: |
          if [ -f index.html ] && [ -f index.css ]; then
            echo "Archivos HTML y CSS encontrados." Â¡CI Basico superado!
          else
            echo "Error: Faltan archivos index.html o index.css."
            exit 1
          fi

  desplegar_paguina:
    needs: verificar_codigo
    if: github.ref == 'refs/heads/main' 
    
